// <auto-generated />
namespace ShopPrototype.DataAccess.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Salon_data : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Salon_data));
        
        string IMigrationMetadata.Id
        {
            get { return "201609102015516_Salon_data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
