// <auto-generated />
namespace ShopPrototype.DataAccess.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class salon_facility : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(salon_facility));
        
        string IMigrationMetadata.Id
        {
            get { return "201609041726135_salon_facility"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
